# Generated by Django 3.1.3 on 2020-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essportfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='my_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
