# Generated by Django 3.1.3 on 2020-11-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essportfolioapp', '0002_auto_20201130_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='user',
        ),
    ]
