# Generated by Django 3.1.3 on 2020-11-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essportfolioapp', '0003_remove_aboutme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='fb_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='li_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='t_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
